### ISSUE TITLE
Buttons on profile page don't work

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/worms#43]
http://www.wormwatchlab.org/#/profile

The "recents," "favorites," and numbered page buttons at the bottom of a Worm Watch Lab profile page all do not work. Completely broken.

(Need to have at least 13 classifications to see the pages at the bottom.)

**Comment by aweiksnar** [comment]
@DarrenMcRoy Should be fixed with 2e04f2f. re-open if you disagree

**Comment by aweiksnar** [comment]
(actually) closed with 075ac8eb3a07d4396feb76803b66564230299c86
