### ISSUE TITLE
Goal on front page is complete again

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/worms#45]
200,000 has been achieved, and going!

We should update the front page, either with a new goal, or to remove the goal bar and put in statistics for numbers of videos completed, active, etc... ?

**Comment by chrissnyder** [comment]
I'd rather swap it to the line of statistics so I don't have to update it every couple of weeks. @mrniaboc is the event over? Can I remove the reference to BSW?

**Comment by mrniaboc** [comment]
Yes. It's over. We won. You can take down the BSA stuff.

**Comment by chrissnyder** [comment]
Closed via @9154cd737ea060400ad25ec7e7dcf541167826fd
