### ISSUE TITLE
Unplayable black/blank videos

### ISSUE THREAD

**Issue by brianaharder** [zooniverse/worms#46]
Multiple users are seeing blank videos. The video doesn't play, showing only a black screen with loading icons.  Because the video doesn't play, they can't be retired normally by being classified, it seems that the super users are seeing these more and more often.

IDs of the videos that are broken, more can be provided if needed.  

51c2082e2d5d3ad242012144
51c2082e2d5d3ad242012145 
51c2082e2d5d3ad242012140 
51c2082e2d5d3ad24201213f

**Comment by chrissnyder** [comment]
Ah, definitely something wrong. All those subjects given me `Access Denied` errors when I try to view the videos. That error typically occurs when nothing exists at that location, which means something failed when the video was uploaded.

I'll look into fixing this today.

**Comment by brianaharder** [comment]
A couple more, it looks like they're all around the same ID.  

51c2082e2d5d3ad242012143
51c2082e2d5d3ad242012141

This one was reported as having a preview image, but no video to load.

51c2082e2d5d3ad24201213d

**Comment by chrissnyder** [comment]
@brianaharder I've removed all those videos from circulation. I do need to scan all subjects to fix this more generally, but the immediate problem should be solved.

That said, I'll leave the issue open for any other reports of broken subjects.

**Comment by brianaharder** [comment]
Reported earlier today:

51c2082e2d5d3ad24201213d - again
51c2082e2d5d3ad242012142

**Comment by chrissnyder** [comment]
```
51c2082e2d5d3ad24201213d - again
51c2082e2d5d3ad242012142
```

Removed.

**Comment by chrissnyder** [comment]
Current dataset is complete, so closing this. There might be more data in the near future, but don't know any specific timeframes.
