### ISSUE TITLE
User out of videos?

### ISSUE THREAD

**Issue by brianaharder** [zooniverse/worms#47]
User JJBehr ( ID 51033b0fdea6536c07000035 if that's a better way to look him up. ) is reporting that he's only able to view 9 videos before the 'next worm' button stops responding and he has to refresh the page and/or relaunch his web browser, after which he can get another 9 videos to watch.  He's also reporting repeats of previously viewed videos; most of the videos on WWL are unremarkable so it's hard to say if they're *all* repeats.  Tested on Chrome and Safari.

I suspect this user had viewed all the remaining videos, and that's what's causing him such odd problems.  Hoping to sort out if it's a weird bug stopping him from classifying or if he's finished everything available!

**Comment by chrissnyder** [comment]
JJBehr has done nearly 29,000 classifications on WWL, so yea, definitely him running out of active data.

Would be better if we had a message to pop up when a user has run dry, but I don't think we'll be able to swing to front-end dev on WWL anytime soon.

**Comment by brianaharder** [comment]
Thank you!  A message would be better for sure, but unless WWL has more
data planned, the project is reaching end of life, so I don't expect any
dev time.
